In [1]:
import pandas as pd 


df = pd.read_csv('D:/Data Science/FYP_Material/Sentiment Analysis/Text_datasets/Dataset-SA.csv')

df.head(5)

,product_name,product_price,Rate,Review,Summary,Sentiment
0,Candes 12 L Room/Personal Air Cooler??????(Whi...,3999,5,super!,great cooler excellent air flow and for this p...,positive
1,Candes 12 L Room/Personal Air Cooler??????(Whi...,3999,5,awesome,best budget 2 fit cooler nice cooling,positive
2,Candes 12 L Room/Personal Air Cooler??????(Whi...,3999,3,fair,the quality is good but the power of air is de...,positive
3,Candes 12 L Room/Personal Air Cooler??????(Whi...,3999,1,useless product,very bad product its a only a fan,negative
4,Candes 12 L Room/Personal Air Cooler??????(Whi...,3999,3,fair,ok ok product,neutral

Data Analysis

Value counts in sentiment column

In [3]:
df['Sentiment'].value_counts()

Sentiment
positive    166579
negative     28234
neutral      10239
Name: count, dtype: int64

! --------------------------------------- Analysing value counts in product_name column ----------------------------!

In [62]:
df['product_name'].value_counts()

product_name
cello Pack of 18 Opalware Cello Dazzle Lush Fiesta Opalware Dinner Set, 18 Pieces Dinner SetÃÂ ÃÂ (White, Microwave Safe)    6005
Lakm?? Eyeconic Kajal Twin Pack??????????(Deep Black, 0.7 g)                                                                   5000
Mi 5A 80 cm (32 inch) HD Ready LED Smart Android TV with Dolby Audio (2022 Model)                                              2205
cello Pack of 18 Opalware Cello Dazzle Lush Fiesta Opalware Dinner Set 18 Pieces Dinner SetWhite Microwave Safe                2095
Home Sizzler 153 cm 502 ft Polyester Room Darkening Window Curtain Pack Of 2Floral Brown                                       2012
                                                                                                                               ...
LA VERNE Self Design Double Mink Blanket for  Heavy WinterWoollen Blend Pink                                                      5
Stylish Brown Sports Men Watches Multifunctional Luxury Waterproof Modern Digital Watch   For Men                                 5
VH000008C Analog Watch  - For Women                                                                                               4
VH000008D Analog Watch  - For Women                                                                                               4
LS2917 Mesh Strap All Black Avatar Day and Date Functioning Quartz Analog Watch   For Men                                         2
Name: count, Length: 958, dtype: int64

In [40]:
val_C_P = df['product_name'].value_counts()

In [66]:
val_C_P_above_1k = valC[valC > 1000]

val_C_P_above_1k

product_name
cello Pack of 18 Opalware Cello Dazzle Lush Fiesta Opalware Dinner Set, 18 Pieces Dinner SetÃÂ ÃÂ (White, Microwave Safe)                     6005
Lakm?? Eyeconic Kajal Twin Pack??????????(Deep Black, 0.7 g)                                                                                    5000
Mi 5A 80 cm (32 inch) HD Ready LED Smart Android TV with Dolby Audio (2022 Model)                                                               2205
cello Pack of 18 Opalware Cello Dazzle Lush Fiesta Opalware Dinner Set 18 Pieces Dinner SetWhite Microwave Safe                                 2095
Home Sizzler 153 cm 502 ft Polyester Room Darkening Window Curtain Pack Of 2Floral Brown                                                        2012
Mi 3i 10000 mAh Power Bank (Fast Charging, 18W)ÐÒ?ÐÓ®ÐÂ ÐÒ?ÐÓ®ÐÂ (Blue, Lithium Polymer)                                                2006
Singer FM 1409 Electric Sewing MachineÐÒ?ÐÓ®ÐÂ ÐÒ?ÐÓ®ÐÂ ( Built-in Stitches 9)                                                          2003
Men Cargos                                                                                                                                      2000
SAMSUNG EVO Plus 64 GB MicroSDXC Class 10 95 MBs  Memory CardWith Adapter                                                                       1999
POCO C31 (Royal Blue, 64 GB)?ÐÒÐÒ?ÐÒÐÒ(4 GB RAM)                                                                                        1999
HAIR & CARE Triple Blend Damage Repair Non-Sticky Hair Oil with Aloe Vera, For Dry, Rough, & Frizzy Hair, Hair OilÐÓ®ÐÂ ÐÓ®ÐÂ (400 ml)      1999
Lakm?? Eyeconic Kajal Twin Pack??????(Deep Black, 0.7 g)                                                                                        1999
MILTON Thermosteel Flip Lid 500 ml FlaskPack of 1 Silver Steel                                                                                  1983
DOMS Pencil Smart Kit                                                                                                                           1961
Pigeon Favourite Electric Kettle??????(1.5 L, Silver, Black)                                                                                    1880
Canon EOS 3000D DSLR Camera 1 Camera Body, 18 - 55 mm Lens????????(Black)                                                                       1829
NIVIA Storm Football - Size: 5ÐÓ®ÐÂ ÐÓ®ÐÂ (Pack of 1, Multicolor)                                                                           1802
Bajaj DX 2 LW Dry Iron                                                                                                                          1791
LA VERNE Microfibre Stripes Cushion Pack of 3White                                                                                              1770
CMerchants Multi Organiser BLue4 Book Shelf Metal Open Book ShelfFinish Color  BLUE DIYDoItYourself                                             1769
BAJAJ 15 L Storage Water Geyser (Popular Plus 15 L, White)                                                                                      1755
SAMSUNG 253 L Frost Free Double Door 3 Star RefrigeratorÐÒ?ÐÓ®ÐÂ ÐÒ?ÐÓ®ÐÂ (Elegant Inox, RT28A3453S8/HL)                                1727
Men Graphic Print Round Neck Black T-Shirt                                                                                                      1681
Google Nest Mini (2nd Gen) with Google Assistant Smart Speaker??????(Chalk)                                                                     1662
boAt Wave Neo with 1.69 inch , 2.5D Curved Display & Multiple Sports Modes SmartwatchÐÒ?ÐÓ®ÐÂ ÐÒ?ÐÓ®ÐÂ (Burgundy Strap, Free Size)      1617
MarQ by Flipkart 18-Litre 18L1200W4HL Oven Toaster Grill (OTG) with 4 Skewers and Crumb TrayÐÓ®ÐÂ ÐÓ®ÐÂ (Black)                             1603
AGARO Regal Hand-held Vacuum CleanerÐÒ?ÐÓ®ÐÂ ÐÒ?ÐÓ®ÐÂ (Black)                                                                           1582
VICTORY Professional Wrist Wrap Band , Wrist Strap For Gym and Fitness Wrist Support                                                            1548
Men Regular Fit Black Cotton Blend Trousers                                                                                                     1517
RIAN Animal Single Mink Blanket for  Mild WinterPolyester Brown Grey                                                                            1398
Pack of 2 Solid Men Dark Grey, Grey Casual Shorts                                                                                               1347
Boys Full Sleeve Solid Hooded Sweatshirt                                                                                                        1286
PHILIPS MMS8085B/94 Convertible 80 W Bluetooth Home TheatreÐÓ®ÐÂ ÐÓ®ÐÂ (Black, 2.1 Channel)                                                 1231
Thomson Alpha 80 cm (32 inch) HD Ready LED Smart Linux TV with 30 W Sound Output & Bezel-Less DesignÐÒ?ÐÓ®ÐÂ ÐÒ?ÐÓ®ÐÂ (32Alpha007BL)    1200
Crompton 75 L Desert Air Cooler??????(White, Teal, ACGC-DAC751)                                                                                 1183
Printed Men Three Fourths                                                                                                                       1118
BAJAJ Crest Neo 1200 mm 3 Blade Ceiling Fan??????????(White, Pack of 1)                                                                         1108
SportSoul Cotton Gym & Athletic Abdomen Support??????(Grey, Black)                                                                              1100
VH000010A Analog Watch  - For Women                                                                                                             1093
Dettol Effective Protection Antiseptic LiquidÐÓ®ÐÂ ÐÓ®ÐÂ (1000 ml)                                                                          1058
APPLE iPad (9th Gen) 64 GB ROM 10.2 inch with Wi-Fi Only (Space Grey)                                                                           1043
Tanunni Mobile Holder Mobile Holder                                                                                                             1024
Name: count, dtype: int64

In [68]:
len(valC[valC > 1000])

42

!--------------------------- Now checking positive, negative and neutral split for the each product ---------------------!

Crompton 75 L Desert Air Cooler??????(White, Teal, ACGC-DAC751)

In [5]:
airCooler_75_df = df[df['product_name'] == 'Crompton 75 L Desert Air Cooler??????(White, Teal, ACGC-DAC751)']

airCooler_75_df

,product_name,product_price,Rate,Review,Summary,Sentiment
816,"Crompton 75 L Desert Air Cooler??????(White, T...",9999,5,simply awesome,its really worth every single penny it works l...,positive
817,"Crompton 75 L Desert Air Cooler??????(White, T...",9999,4,worth the money . desert cooler live up to the...,i bought crompton ozone 75 desert air cooler i...,positive
818,"Crompton 75 L Desert Air Cooler??????(White, T...",9999,5,worth every penny,great packaging by seller as this was the most...,positive
819,"Crompton 75 L Desert Air Cooler??????(White, T...",9999,5,fabulous!,delivery was delayed by two days except this e...,positive
820,"Crompton 75 L Desert Air Cooler??????(White, T...",9999,5,super!,cant go wrong with crompton brand in punjab th...,positive
...,...,...,...,...,...,...
1994,"Crompton 75 L Desert Air Cooler??????(White, T...",9999,4,worth the money,good,positive
1995,"Crompton 75 L Desert Air Cooler??????(White, T...",9999,5,classy product,nice product,positive
1996,"Crompton 75 L Desert Air Cooler??????(White, T...",9999,4,really nice,good,positive
1997,"Crompton 75 L Desert Air Cooler??????(White, T...",9999,4,very good,nice big size product and performance but ther...,neutral
1998,"Crompton 75 L Desert Air Cooler??????(White, T...",9999,5,terrific,1 the fan speed was too good 2 cooling is very...,positive

In [7]:
print('Positive: ')
print(len(
    airCooler_75_df[airCooler_75_df['Sentiment'] == 'positive'])
     )

print('Negative: ')
print(len(
    airCooler_75_df[airCooler_75_df['Sentiment'] == 'negative'])
     )

print('Neutral: ')
print(len(
    airCooler_75_df[airCooler_75_df['Sentiment'] == 'neutral'])
     )

Positive:
955
Negative:
188
Neutral:
40

MAHARAJA WHITELINE 65 L Desert Air Cooler??????(White, Grey, Rambo Grey / AC-303)

In [11]:
airCooler_65_df = df[df['product_name'] == 'MAHARAJA WHITELINE 65 L Desert Air Cooler??????(White, Grey, Rambo Grey / AC-303)']

airCooler_65_df

,product_name,product_price,Rate,Review,Summary,Sentiment
36,MAHARAJA WHITELINE 65 L Desert Air Cooler?????...,7999,5,wonderful,the best poduct that i bought from flifkart it...,positive
37,MAHARAJA WHITELINE 65 L Desert Air Cooler?????...,7999,4,good quality product,cooler is big and wide maharaja brand trust y ...,positive
38,MAHARAJA WHITELINE 65 L Desert Air Cooler?????...,7999,5,awesome,it is one of the best air coolers at reasonabl...,positive
39,MAHARAJA WHITELINE 65 L Desert Air Cooler?????...,7999,5,excellent,awesome air cooleri was looking for a cooler u...,positive
40,MAHARAJA WHITELINE 65 L Desert Air Cooler?????...,7999,5,great product,purchased after a lot of discussions and revie...,positive
...,...,...,...,...,...,...
811,MAHARAJA WHITELINE 65 L Desert Air Cooler?????...,7999,3,just okay,air flow is not sufficient speed of fan is low...,positive
812,MAHARAJA WHITELINE 65 L Desert Air Cooler?????...,7999,5,best in the market!,nice,positive
813,MAHARAJA WHITELINE 65 L Desert Air Cooler?????...,7999,4,value-for-money,nice product on time delivery,positive
814,MAHARAJA WHITELINE 65 L Desert Air Cooler?????...,7999,5,wonderful,super cooling,positive
815,MAHARAJA WHITELINE 65 L Desert Air Cooler?????...,7999,5,hated it!,awesome product,positive

In [13]:
print('Positive: ')
print(len(
    airCooler_65_df[airCooler_65_df['Sentiment'] == 'positive'])
     )

print('Negative: ')
print(len(
    airCooler_65_df[airCooler_65_df['Sentiment'] == 'negative'])
     )

print('Neutral: ')
print(len(
    airCooler_65_df[airCooler_65_df['Sentiment'] == 'neutral'])
     )

Positive:
649
Negative:
97
Neutral:
34

APPLE iPad (9th Gen) 64 GB ROM 10.2 inch with Wi-Fi Only (Space Grey)

In [17]:
appleIpad_df = df[df['product_name'] == 'APPLE iPad (9th Gen) 64 GB ROM 10.2 inch with Wi-Fi Only (Space Grey)']

appleIpad_df

,product_name,product_price,Rate,Review,Summary,Sentiment
120749,APPLE iPad (9th Gen) 64 GB ROM 10.2 inch with ...,29990,4,really nice,this is my first apple product i am using this...,positive
120750,APPLE iPad (9th Gen) 64 GB ROM 10.2 inch with ...,29990,5,awesome,everything is very good and box is very good c...,positive
120751,APPLE iPad (9th Gen) 64 GB ROM 10.2 inch with ...,29990,5,must buy!,i bought silver colour which is really awesome...,positive
120752,APPLE iPad (9th Gen) 64 GB ROM 10.2 inch with ...,29990,5,fabulous!,best performance in this range no other tab ca...,positive
120753,APPLE iPad (9th Gen) 64 GB ROM 10.2 inch with ...,29990,5,terrific purchase,its very good ipad its too much big sreen you ...,positive
...,...,...,...,...,...,...
121787,APPLE iPad (9th Gen) 64 GB ROM 10.2 inch with ...,29990,5,excellent,very good product its really wonderful this is...,positive
121788,APPLE iPad (9th Gen) 64 GB ROM 10.2 inch with ...,29990,5,terrific purchase,it is my first tablet bought it for notes stud...,positive
121789,APPLE iPad (9th Gen) 64 GB ROM 10.2 inch with ...,29990,5,wonderful,performance battery back up and screen is exce...,positive
121790,APPLE iPad (9th Gen) 64 GB ROM 10.2 inch with ...,29990,5,must buy!,very useful,positive
121791,APPLE iPad (9th Gen) 64 GB ROM 10.2 inch with ...,29990,5,perfect product!,perfect,positive

In [19]:
print('Positive: ')
print(len(
    appleIpad_df[appleIpad_df['Sentiment'] == 'positive'])
     )

print('Negative: ')
print(len(
    appleIpad_df[appleIpad_df['Sentiment'] == 'negative'])
     )

print('Neutral: ')
print(len(
    appleIpad_df[appleIpad_df['Sentiment'] == 'neutral'])
     )

Positive:
974
Negative:
54
Neutral:
15

MILTON Thermosteel Flip Lid 500 ml FlaskPack of 1 Silver Steel

In [23]:
thermoSteel_df = df[df['product_name'] == 'MILTON Thermosteel Flip Lid 500 ml FlaskPack of 1 Silver Steel']

thermoSteel_df

,product_name,product_price,Rate,Review,Summary,Sentiment
180165,MILTON Thermosteel Flip Lid 500 ml FlaskPack o...,648,5,awesome,nice it good quality thanks flipkart good hot ...,positive
180166,MILTON Thermosteel Flip Lid 500 ml FlaskPack o...,648,5,excellent,product is very good and leakproofapprox 12 ho...,positive
180167,MILTON Thermosteel Flip Lid 500 ml FlaskPack o...,648,5,great product,received properly same like description very u...,positive
180168,MILTON Thermosteel Flip Lid 500 ml FlaskPack o...,648,5,best in the market!,trust me no leakage and hot or cool 24 hr work...,positive
180169,MILTON Thermosteel Flip Lid 500 ml FlaskPack o...,648,5,great product,good product had taken it for my mom as she ne...,positive
...,...,...,...,...,...,...
182143,MILTON Thermosteel Flip Lid 500 ml FlaskPack o...,648,4,wonderful,nice,positive
182144,MILTON Thermosteel Flip Lid 500 ml FlaskPack o...,648,5,highly recommended,good,positive
182145,MILTON Thermosteel Flip Lid 500 ml FlaskPack o...,648,5,great product,best,positive
182146,MILTON Thermosteel Flip Lid 500 ml FlaskPack o...,648,5,best in the market!,nice,positive
182147,MILTON Thermosteel Flip Lid 500 ml FlaskPack o...,648,5,excellent,thank you flipkart for such a good product,positive

In [25]:
print('Positive: ')
print(len(
    thermoSteel_df[thermoSteel_df['Sentiment'] == 'positive'])
     )

print('Negative: ')
print(len(
    thermoSteel_df[thermoSteel_df['Sentiment'] == 'negative'])
     )

print('Neutral: ')
print(len(
    thermoSteel_df[thermoSteel_df['Sentiment'] == 'neutral'])
     )

Positive:
1776
Negative:
149
Neutral:
58

Google Nest Mini (2nd Gen) with Google Assistant Smart Speaker??????(Chalk)

In [29]:
googleAssistant_df = df[df['product_name'] == 'Google Nest Mini (2nd Gen) with Google Assistant Smart Speaker??????(Chalk)']

googleAssistant_df

,product_name,product_price,Rate,Review,Summary,Sentiment
24550,Google Nest Mini (2nd Gen) with Google Assista...,3499,5,"does what it says, amazing service from flipkart",for beginners in summary this is a device with...,positive
24551,Google Nest Mini (2nd Gen) with Google Assista...,3499,4,delightful,its good smart speaker but i see one cons ther...,positive
24552,Google Nest Mini (2nd Gen) with Google Assista...,3499,2,slightly disappointed,not much useful because of restrictions1 canno...,negative
24553,Google Nest Mini (2nd Gen) with Google Assista...,3499,5,simply awesome,this is an awesome product and very amazing im...,positive
24554,Google Nest Mini (2nd Gen) with Google Assista...,3499,5,super!,this is the first time that i have used a goog...,positive
...,...,...,...,...,...,...
26207,Google Nest Mini (2nd Gen) with Google Assista...,3499,4,delightful,everything is fine but not battery backup,positive
26208,Google Nest Mini (2nd Gen) with Google Assista...,3499,4,wonderful,good sounds quality,positive
26209,Google Nest Mini (2nd Gen) with Google Assista...,3499,5,great product,great purchase if you want smart home,positive
26210,Google Nest Mini (2nd Gen) with Google Assista...,3499,5,super!,nice experience highly recommend it for casual...,positive
26211,Google Nest Mini (2nd Gen) with Google Assista...,3499,4,delightful,this is amazing product very good i really lik...,positive

In [31]:
print('Positive: ')
print(len(
    googleAssistant_df[googleAssistant_df['Sentiment'] == 'positive'])
     )

print('Negative: ')
print(len(
    googleAssistant_df[googleAssistant_df['Sentiment'] == 'negative'])
     )

print('Neutral: ')
print(len(
    googleAssistant_df[googleAssistant_df['Sentiment'] == 'neutral'])
     )

Positive:
1294
Negative:
291
Neutral:
77

LA VERNE Microfibre Stripes Cushion Pack of 3White

In [35]:
cusionPack_df = df[df['product_name'] == 'LA VERNE Microfibre Stripes Cushion Pack of 3White']

cusionPack_df

,product_name,product_price,Rate,Review,Summary,Sentiment
155356,LA VERNE Microfibre Stripes Cushion Pack of 3W...,379,5,brilliant,excellent in qualityvery nice and soft just li...,positive
155357,LA VERNE Microfibre Stripes Cushion Pack of 3W...,379,5,classy product,good cushion very soft and works well as my ba...,positive
155358,LA VERNE Microfibre Stripes Cushion Pack of 3W...,379,3,just okay,outer cloth quality is greatfluffyness is adeq...,positive
155359,LA VERNE Microfibre Stripes Cushion Pack of 3W...,379,5,excellent,well good quality in cheapest price range buil...,positive
155360,LA VERNE Microfibre Stripes Cushion Pack of 3W...,379,2,slightly disappointed,the cushions from la verne are extremely soft ...,negative
...,...,...,...,...,...,...
157121,LA VERNE Microfibre Stripes Cushion Pack of 3W...,379,5,worth every penny,nice cushions good meterial,positive
157122,LA VERNE Microfibre Stripes Cushion Pack of 3W...,379,4,very good,good productbefore time deliveryi like it,positive
157123,LA VERNE Microfibre Stripes Cushion Pack of 3W...,379,1,very poor,very bad quality,negative
157124,LA VERNE Microfibre Stripes Cushion Pack of 3W...,379,4,nice product,product was good but devilary timings were not...,positive
157125,LA VERNE Microfibre Stripes Cushion Pack of 3W...,379,5,worth every penny,awesome pillow,positive

In [37]:
print('Positive: ')
print(len(
    cusionPack_df[cusionPack_df['Sentiment'] == 'positive'])
     )

print('Negative: ')
print(len(
    cusionPack_df[cusionPack_df['Sentiment'] == 'negative'])
     )

print('Neutral: ')
print(len(
    cusionPack_df[cusionPack_df['Sentiment'] == 'neutral'])
     )

Positive:
1555
Negative:
119
Neutral:
96

Bajaj DX 2 LW Dry Iron

In [41]:
dryIron_df = df[df['product_name'] == 'Bajaj DX 2 LW Dry Iron']

dryIron_df

,product_name,product_price,Rate,Review,Summary,Sentiment
174110,Bajaj DX 2 LW Dry Iron,529,5,just wow!,it is easy to use lightweight compact worth bu...,positive
174111,Bajaj DX 2 LW Dry Iron,529,5,brilliant,i love it this is the best iron buy now and it...,positive
174112,Bajaj DX 2 LW Dry Iron,529,5,simply awesome,first of all very fast deliverythis iron is ab...,positive
174113,Bajaj DX 2 LW Dry Iron,529,5,simply awesome,very good working also good i am very happy wi...,positive
174114,Bajaj DX 2 LW Dry Iron,529,5,brilliant,super product good quality and easy to iron ou...,positive
...,...,...,...,...,...,...
175896,Bajaj DX 2 LW Dry Iron,529,5,wonderful,very nice,positive
175897,Bajaj DX 2 LW Dry Iron,529,1,not recommended at all,bad quality,negative
175898,Bajaj DX 2 LW Dry Iron,529,5,simply awesome,good,positive
175899,Bajaj DX 2 LW Dry Iron,529,1,utterly disappointed,delivery boy behavior is not good,negative
175900,Bajaj DX 2 LW Dry Iron,529,5,worth every penny,its really good does the job,positive

In [43]:
print('Positive: ')
print(len(
    dryIron_df[dryIron_df['Sentiment'] == 'positive'])
     )

print('Negative: ')
print(len(
    dryIron_df[dryIron_df['Sentiment'] == 'negative'])
     )

print('Neutral: ')
print(len(
    dryIron_df[dryIron_df['Sentiment'] == 'neutral'])
     )

Positive:
1540
Negative:
148
Neutral:
103

Men Graphic Print Round Neck Black T-Shirt

In [47]:
blackTshirt_df = df[df['product_name'] == 'Men Graphic Print Round Neck Black T-Shirt']

blackTshirt_df

,product_name,product_price,Rate,Review,Summary,Sentiment
54550,Men Graphic Print Round Neck Black T-Shirt,269,5,NaN,this product is very good yaar,positive
54551,Men Graphic Print Round Neck Black T-Shirt,269,4,NaN,nice,positive
54552,Men Graphic Print Round Neck Black T-Shirt,269,5,NaN,best product in low price i love flipkart,positive
54553,Men Graphic Print Round Neck Black T-Shirt,269,4,NaN,good,positive
54554,Men Graphic Print Round Neck Black T-Shirt,269,4,NaN,quality awesome,positive
...,...,...,...,...,...,...
56226,Men Graphic Print Round Neck Black T-Shirt,269,2,NaN,quality not okay very thin cloth,negative
56227,Men Graphic Print Round Neck Black T-Shirt,269,5,NaN,good product,positive
56228,Men Graphic Print Round Neck Black T-Shirt,269,2,NaN,poor quality tshirt,negative
56229,Men Graphic Print Round Neck Black T-Shirt,269,1,NaN,faltu profuct and faltu quality,negative
56230,Men Graphic Print Round Neck Black T-Shirt,269,4,NaN,good t shirt,positive

In [148]:
print('Positive: ')
print(len(
    blackTshirt_df[blackTshirt_df['Sentiment'] == 'positive'])
     )

print('Negative: ')
print(len(
    blackTshirt_df[blackTshirt_df['Sentiment'] == 'negative'])
     )

print('Neutral: ')
print(len(
    blackTshirt_df[blackTshirt_df['Sentiment'] == 'neutral'])
     )

Positive:
1093
Negative:
489
Neutral:
99

Canon EOS 3000D DSLR Camera 1 Camera Body, 18 - 55 mm Lens????????(Black)

In [49]:
dslrCamera_df = df[df['product_name'] == 'Canon EOS 3000D DSLR Camera 1 Camera Body, 18 - 55 mm Lens????????(Black)']

dslrCamera_df

,product_name,product_price,Rate,Review,Summary,Sentiment
5999,"Canon EOS 3000D DSLR Camera 1 Camera Body, 18 ...",30999,4,really nice,the product is very good but if i take another...,positive
6000,"Canon EOS 3000D DSLR Camera 1 Camera Body, 18 ...",30999,5,excellent,product really great i am totally sctified thi...,positive
6001,"Canon EOS 3000D DSLR Camera 1 Camera Body, 18 ...",30999,5,great product,well reviewing this after using for almost one...,positive
6002,"Canon EOS 3000D DSLR Camera 1 Camera Body, 18 ...",30999,5,just wow!,worth more than the amount best dslr for a goo...,positive
6003,"Canon EOS 3000D DSLR Camera 1 Camera Body, 18 ...",30999,3,does the job,satisfied with the product its a really good f...,positive
...,...,...,...,...,...,...
7823,"Canon EOS 3000D DSLR Camera 1 Camera Body, 18 ...",30999,5,perfect product!,this is awesome product for beginners,positive
7824,"Canon EOS 3000D DSLR Camera 1 Camera Body, 18 ...",30999,5,mind-blowing purchase,my first camera in very good,positive
7825,"Canon EOS 3000D DSLR Camera 1 Camera Body, 18 ...",30999,5,awesome,good product,positive
7826,"Canon EOS 3000D DSLR Camera 1 Camera Body, 18 ...",30999,5,nice camera,as per your budget and entry level beginner it...,positive
7827,"Canon EOS 3000D DSLR Camera 1 Camera Body, 18 ...",30999,5,wonderful,awesome camera got it for 19700,positive

In [143]:
print('Positive: ')
print(len(
    dslrCamera_df[dslrCamera_df['Sentiment'] == 'positive'])
     )

print('Negative: ')
print(len(
    dslrCamera_df[dslrCamera_df['Sentiment'] == 'negative'])
     )

print('Neutral: ')
print(len(
    dslrCamera_df[dslrCamera_df['Sentiment'] == 'neutral'])
     )

Positive:
1635
Negative:
124
Neutral:
70

SAMSUNG EVO Plus 64 GB MicroSDXC Class 10 95 MBs  Memory CardWith Adapter

In [51]:
memoryCard_df = df[df['product_name'] == 'SAMSUNG EVO Plus 64 GB MicroSDXC Class 10 95 MBs  Memory CardWith Adapter']

memoryCard_df

,product_name,product_price,Rate,Review,Summary,Sentiment
188145,SAMSUNG EVO Plus 64 GB MicroSDXC Class 10 95 M...,649,5,simply awesome,total free space available is 596 gb i was abl...,positive
188146,SAMSUNG EVO Plus 64 GB MicroSDXC Class 10 95 M...,649,5,classy product,wow must buy this speed in transfer files is n...,positive
188147,SAMSUNG EVO Plus 64 GB MicroSDXC Class 10 95 M...,649,5,great product,very nice awesome memory card when i inserted ...,positive
188148,SAMSUNG EVO Plus 64 GB MicroSDXC Class 10 95 M...,649,5,must buy!,nice product now my samsung m31 is more faster...,positive
188149,SAMSUNG EVO Plus 64 GB MicroSDXC Class 10 95 M...,649,5,classy product,i have loved the product given by flipkart i a...,positive
...,...,...,...,...,...,...
190139,SAMSUNG EVO Plus 64 GB MicroSDXC Class 10 95 M...,649,5,must buy!,nice product,positive
190140,SAMSUNG EVO Plus 64 GB MicroSDXC Class 10 95 M...,649,4,very good,hey its very goodmy internal storage problem h...,negative
190141,SAMSUNG EVO Plus 64 GB MicroSDXC Class 10 95 M...,649,5,terrific purchase,as expected,positive
190142,SAMSUNG EVO Plus 64 GB MicroSDXC Class 10 95 M...,649,3,nice,samsung evo plus 64gb sd card is good processi...,positive
190143,SAMSUNG EVO Plus 64 GB MicroSDXC Class 10 95 M...,649,4,delightful,very good producti have 3 year experience with...,positive

In [135]:
print('Positive: ')
print(len(
    memoryCard_df[memoryCard_df['Sentiment'] == 'positive'])
     )

print('Negative: ')
print(len(
    memoryCard_df[memoryCard_df['Sentiment'] == 'negative'])
     )

print('Neutral: ')
print(len(
    memoryCard_df[memoryCard_df['Sentiment'] == 'neutral'])
     )

Positive:
1808
Negative:
113
Neutral:
78

Home Sizzler 153 cm 502 ft Polyester Room Darkening Window Curtain Pack Of 2Floral Brown

In [53]:
windowCurtain_df = df[df['product_name'] == 'Home Sizzler 153 cm 502 ft Polyester Room Darkening Window Curtain Pack Of 2Floral Brown']

windowCurtain_df

,product_name,product_price,Rate,Review,Summary,Sentiment
152694,Home Sizzler 153 cm 502 ft Polyester Room Dark...,299,4,good choice,nice product but should have been thick then w...,positive
152695,Home Sizzler 153 cm 502 ft Polyester Room Dark...,299,5,mind-blowing purchase,superb curtains cloth quality is also superb a...,positive
152696,Home Sizzler 153 cm 502 ft Polyester Room Dark...,299,5,best in the market!,very nice for the price range we have an 8 ft ...,positive
152697,Home Sizzler 153 cm 502 ft Polyester Room Dark...,299,5,best in the market!,1the quality is quite good at this price range...,positive
152698,Home Sizzler 153 cm 502 ft Polyester Room Dark...,299,5,fabulous!,pros best curtain in the price colour design f...,positive
...,...,...,...,...,...,...
154701,Home Sizzler 153 cm 502 ft Polyester Room Dark...,299,5,worth every penny,very very nice product i like it,positive
154702,Home Sizzler 153 cm 502 ft Polyester Room Dark...,299,4,good choice,amazing,positive
154703,Home Sizzler 153 cm 502 ft Polyester Room Dark...,299,4,pretty good,good,positive
154704,Home Sizzler 153 cm 502 ft Polyester Room Dark...,299,4,nice product,good,positive
154705,Home Sizzler 153 cm 502 ft Polyester Room Dark...,299,4,good quality product,very good quality,positive

In [128]:
print('Positive: ')
print(len(
    windowCurtain_df[windowCurtain_df['Sentiment'] == 'positive'])
     )

print('Negative: ')
print(len(
    windowCurtain_df[windowCurtain_df['Sentiment'] == 'negative'])
     )

print('Neutral: ')
print(len(
    windowCurtain_df[windowCurtain_df['Sentiment'] == 'neutral'])
     )

Positive:
1840
Negative:
75
Neutral:
97

BAJAJ 15 L Storage Water Geyser (Popular Plus 15 L, White)

In [55]:
waterGeyser_df = df[df['product_name'] == 'BAJAJ 15 L Storage Water Geyser (Popular Plus 15 L, White)']

waterGeyser_df

,product_name,product_price,Rate,Review,Summary,Sentiment
130993,BAJAJ 15 L Storage Water Geyser (Popular Plus ...,5499,4,wonderful,i am giving four stars because of the courier ...,positive
130994,BAJAJ 15 L Storage Water Geyser (Popular Plus ...,5499,5,wonderful,product look good and installation is quite ea...,positive
130995,BAJAJ 15 L Storage Water Geyser (Popular Plus ...,5499,5,brilliant,nice product i review it after use 7 to 8 days...,positive
130996,BAJAJ 15 L Storage Water Geyser (Popular Plus ...,5499,5,just wow!,very good product 100100 always on bajaj produ...,positive
130997,BAJAJ 15 L Storage Water Geyser (Popular Plus ...,5499,3,good,overall product is very good and very fast fre...,positive
...,...,...,...,...,...,...
132743,BAJAJ 15 L Storage Water Geyser (Popular Plus ...,5499,4,worth the money,nice,positive
132744,BAJAJ 15 L Storage Water Geyser (Popular Plus ...,5499,4,nice product,good,positive
132745,BAJAJ 15 L Storage Water Geyser (Popular Plus ...,5499,3,good,liked itbut there is no 3pin 16 a plug top wit...,negative
132746,BAJAJ 15 L Storage Water Geyser (Popular Plus ...,5499,5,terrific,i received the item but geyser isnt install ti...,neutral
132747,BAJAJ 15 L Storage Water Geyser (Popular Plus ...,5499,3,just okay,very good,positive

In [123]:
print('Positive: ')
print(len(
    waterGeyser_df[waterGeyser_df['Sentiment'] == 'positive'])
     )

print('Negative: ')
print(len(
    waterGeyser_df[waterGeyser_df['Sentiment'] == 'negative'])
     )

print('Neutral: ')
print(len(
    waterGeyser_df[waterGeyser_df['Sentiment'] == 'neutral'])
     )

Positive:
1513
Negative:
193
Neutral:
49

DOMS Pencil Smart Kit

In [57]:
pencil_df = df[df['product_name'] == 'DOMS Pencil Smart Kit']

pencil_df

,product_name,product_price,Rate,Review,Summary,Sentiment
37589,DOMS Pencil Smart Kit,449,5,excellent,super amazing i loved it a lot thank you flipk...,positive
37590,DOMS Pencil Smart Kit,449,5,simply awesome,thank you so much for this affordable smart ki...,positive
37591,DOMS Pencil Smart Kit,449,5,classy product,the kit is just amazing for like newbies and k...,positive
37592,DOMS Pencil Smart Kit,449,5,worth every penny,this product is so nice i like this product ve...,positive
37593,DOMS Pencil Smart Kit,449,5,terrific purchase,very nice my kis was very happy she loved it v...,positive
...,...,...,...,...,...,...
39545,DOMS Pencil Smart Kit,449,5,highly recommended,excellent product,positive
39546,DOMS Pencil Smart Kit,449,5,just wow!,this doms kit is awesome,positive
39547,DOMS Pencil Smart Kit,449,5,mind-blowing purchase,awesome,positive
39548,DOMS Pencil Smart Kit,449,5,brilliant,nicr,positive
39549,DOMS Pencil Smart Kit,449,5,excellent,very nice,positive

In [118]:
print('Positive: ')
print(len(
    pencil_df[pencil_df['Sentiment'] == 'positive'])
     )

print('Negative: ')
print(len(
    pencil_df[pencil_df['Sentiment'] == 'negative'])
     )

print('Neutral: ')
print(len(
    pencil_df[pencil_df['Sentiment'] == 'neutral'])
     )

Positive:
1900
Negative:
33
Neutral:
28

Pigeon Favourite Electric Kettle??????(1.5 L, Silver, Black

In [59]:
elctricKettle_df = df[df['product_name'] == 'Pigeon Favourite Electric Kettle??????(1.5 L, Silver, Black)']

elctricKettle_df

,product_name,product_price,Rate,Review,Summary,Sentiment
16658,"Pigeon Favourite Electric Kettle??????(1.5 L, ...",699,4,pretty good,great product for hostel people i just love ma...,positive
16659,"Pigeon Favourite Electric Kettle??????(1.5 L, ...",699,5,brilliant,nice and useful kettle for daily use especiall...,positive
16660,"Pigeon Favourite Electric Kettle??????(1.5 L, ...",699,4,value-for-money,15l of quantity in such good price is awsmm fo...,positive
16661,"Pigeon Favourite Electric Kettle??????(1.5 L, ...",699,5,fabulous!,very useful and efficientit works very fastlot...,positive
16662,"Pigeon Favourite Electric Kettle??????(1.5 L, ...",699,4,awesome,nice product n easy to use strongly recommende...,positive
...,...,...,...,...,...,...
18533,"Pigeon Favourite Electric Kettle??????(1.5 L, ...",699,5,terrific,super,positive
18534,"Pigeon Favourite Electric Kettle??????(1.5 L, ...",699,1,worst experience ever!,bad quality of lid,negative
18535,"Pigeon Favourite Electric Kettle??????(1.5 L, ...",699,5,simply awesome,vary good product,positive
18536,"Pigeon Favourite Electric Kettle??????(1.5 L, ...",699,4,nice product,good for value,positive
18537,"Pigeon Favourite Electric Kettle??????(1.5 L, ...",699,4,really nice,nice,positive

In [111]:
print('Positive: ')
print(len(
    elctricKettle_df[elctricKettle_df['Sentiment'] == 'positive'])
     )

print('Negative: ')
print(len(
    elctricKettle_df[elctricKettle_df['Sentiment'] == 'negative'])
     )

print('Neutral: ')
print(len(
    elctricKettle_df[elctricKettle_df['Sentiment'] == 'neutral'])
     )

Positive:
1445
Negative:
338
Neutral:
97

Mi 5A 80 cm (32 inch) HD Ready LED Smart Android TV with Dolby Audio (2022 Model)

In [61]:
tv_df = df[df['product_name'] == 'Mi 5A 80 cm (32 inch) HD Ready LED Smart Android TV with Dolby Audio (2022 Model)']

tv_df

,product_name,product_price,Rate,Review,Summary,Sentiment
114545,Mi 5A 80 cm (32 inch) HD Ready LED Smart Andro...,13999,5,terrific purchase,this is a detailed review after 7 days please ...,positive
114546,Mi 5A 80 cm (32 inch) HD Ready LED Smart Andro...,13999,5,awesome,super and good quality full hd internet also s...,positive
114547,Mi 5A 80 cm (32 inch) HD Ready LED Smart Andro...,13999,4,very good,i m posting review after checking all its func...,positive
114548,Mi 5A 80 cm (32 inch) HD Ready LED Smart Andro...,13999,4,delightful,this mi tv is superb and value for money waiti...,positive
114549,Mi 5A 80 cm (32 inch) HD Ready LED Smart Andro...,13999,4,nice product,i love this mi tv good quality with affordable...,positive
...,...,...,...,...,...,...
116745,Mi 5A 80 cm (32 inch) HD Ready LED Smart Andro...,13999,3,good,ok,neutral
116746,Mi 5A 80 cm (32 inch) HD Ready LED Smart Andro...,13999,4,worth the money,very nice product,positive
116747,Mi 5A 80 cm (32 inch) HD Ready LED Smart Andro...,13999,5,terrific purchase,good product,positive
116748,Mi 5A 80 cm (32 inch) HD Ready LED Smart Andro...,13999,5,simply awesome,supper,positive
116749,Mi 5A 80 cm (32 inch) HD Ready LED Smart Andro...,13999,5,fabulous!,very happy,positive

In [95]:
print('Positive: ')
print(len(
    tv_df[tv_df['Sentiment'] == 'positive'])
     )

print('Negative: ')
print(len(
    tv_df[tv_df['Sentiment'] == 'negative'])
     )

print('Neutral: ')
print(len(
    tv_df[tv_df['Sentiment'] == 'neutral'])
     )

Positive:
1788
Negative:
371
Neutral:
46

Lakm?? Eyeconic Kajal Twin Pack??????????(Deep Black, 0.7 g)

In [63]:
lakmeKajal_df = df[df['product_name'] == 'Lakm?? Eyeconic Kajal Twin Pack??????????(Deep Black, 0.7 g)']

lakmeKajal_df

,product_name,product_price,Rate,Review,Summary,Sentiment
62301,Lakm?? Eyeconic Kajal Twin Pack??????????(Deep...,218,5,highly recommended,highly recommended,positive
62302,Lakm?? Eyeconic Kajal Twin Pack??????????(Deep...,218,5,fabulous!,nice receive the product as expected,positive
62303,Lakm?? Eyeconic Kajal Twin Pack??????????(Deep...,218,5,excellent,super,positive
62304,Lakm?? Eyeconic Kajal Twin Pack??????????(Deep...,218,5,classy product,amazing kajalmust buy,positive
62305,Lakm?? Eyeconic Kajal Twin Pack??????????(Deep...,218,5,just wow!,nice,positive
...,...,...,...,...,...,...
67296,Lakm?? Eyeconic Kajal Twin Pack??????????(Deep...,218,5,must buy!,thanks,positive
67297,Lakm?? Eyeconic Kajal Twin Pack??????????(Deep...,218,4,pretty good,one of my favorite product thanks flipkart for...,positive
67298,Lakm?? Eyeconic Kajal Twin Pack??????????(Deep...,218,5,excellent,nice,positive
67299,Lakm?? Eyeconic Kajal Twin Pack??????????(Deep...,218,4,value-for-money,good,positive
67300,Lakm?? Eyeconic Kajal Twin Pack??????????(Deep...,218,5,great product,very nice,positive

In [89]:
print('Positive: ')
print(len(
    lakmeKajal_df[lakmeKajal_df['Sentiment'] == 'positive'])
     )

print('Negative: ')
print(len(
    lakmeKajal_df[lakmeKajal_df['Sentiment'] == 'negative'])
     )

print('Neutral: ')
print(len(
    lakmeKajal_df[lakmeKajal_df['Sentiment'] == 'neutral'])
     )

Positive:
4692
Negative:
155
Neutral:
153

cello Pack of 18 Opalware Cello Dazzle Lush Fiesta Opalware Dinner Set 18 Pieces Dinner SetWhite Microwave Safe

In [65]:
dinnerSet_df = df[df['product_name'] == 'cello Pack of 18 Opalware Cello Dazzle Lush Fiesta Opalware Dinner Set 18 Pieces Dinner SetWhite Microwave Safe']

dinnerSet_df

,product_name,product_price,Rate,Review,Summary,Sentiment
196952,cello Pack of 18 Opalware Cello Dazzle Lush Fi...,1299,4,worth the money,very good and attractive delicate one can go f...,positive
196953,cello Pack of 18 Opalware Cello Dazzle Lush Fi...,1299,5,fabulous!,just amazing dinner set the quality of the pro...,positive
196954,cello Pack of 18 Opalware Cello Dazzle Lush Fi...,1299,5,mind-blowing purchase,lovely dinner set all r in good condition the ...,positive
196955,cello Pack of 18 Opalware Cello Dazzle Lush Fi...,1299,4,value-for-money,1 good product in cheapest price2 but not that...,positive
196956,cello Pack of 18 Opalware Cello Dazzle Lush Fi...,1299,5,best in the market!,its too good received in good condition packag...,positive
...,...,...,...,...,...,...
199042,cello Pack of 18 Opalware Cello Dazzle Lush Fi...,1299,3,decent product,very small not happy,negative
199043,cello Pack of 18 Opalware Cello Dazzle Lush Fi...,1299,4,pretty good,light weight and very nice product but plates ...,positive
199044,cello Pack of 18 Opalware Cello Dazzle Lush Fi...,1299,5,terrific,super,positive
199045,cello Pack of 18 Opalware Cello Dazzle Lush Fi...,1299,5,excellent,everything came in perfect condition the packa...,positive
199046,cello Pack of 18 Opalware Cello Dazzle Lush Fi...,1299,3,does the job,its not too good but ok,positive

In [99]:
print('Positive: ')
print(len(
    dinnerSet_df[dinnerSet_df['Sentiment'] == 'positive'])
     )

print('Negative: ')
print(len(
    dinnerSet_df[dinnerSet_df['Sentiment'] == 'negative'])
     )

print('Neutral: ')
print(len(
    dinnerSet_df[dinnerSet_df['Sentiment'] == 'neutral'])
     )

Positive:
1888
Negative:
98
Neutral:
109

Men Cargos

In [67]:
menCargo_df = df[df['product_name'] == 'Men Cargos']

menCargo_df

,product_name,product_price,Rate,Review,Summary,Sentiment
50231,Men Cargos,499,4,NaN,nice product i love it but when i wear it the ...,positive
50232,Men Cargos,499,4,NaN,i like this pant,positive
50233,Men Cargos,499,5,NaN,good product,positive
50234,Men Cargos,499,4,NaN,cargo pant is very nice but size is not perfect,negative
50235,Men Cargos,499,4,NaN,good one but cotton quality is not that good o...,negative
...,...,...,...,...,...,...
52226,Men Cargos,399,1,NaN,veryvery bad quality,negative
52227,Men Cargos,399,4,NaN,nice product but,positive
52228,Men Cargos,399,3,NaN,good productworth for moneysize is lower than ...,positive
52229,Men Cargos,399,5,NaN,ever green osam paint,neutral
52230,Men Cargos,399,4,NaN,superb quality fabric is cool for winters even...,positive

In [103]:
print('Positive: ')
print(len(
    menCargo_df[menCargo_df['Sentiment'] == 'positive'])
     )

print('Negative: ')
print(len(
    menCargo_df[menCargo_df['Sentiment'] == 'negative'])
     )

print('Neutral: ')
print(len(
    menCargo_df[menCargo_df['Sentiment'] == 'neutral'])
     )

Positive:
1343
Negative:
421
Neutral:
236

!------------------------------------------------- Balancing the dataset of each product ----------------------------------!

here we are using undersampling to balance the data. 
 - we have taken only 11 different products to make balanced dataframe. airCooler_65_df and airCooler_75_df considered to be one because it is related to air cooler only

In [69]:
# Using groupby to split the dataset by Sentiment type and taking minimum samples from each group
# We will do this process for each of the product dataframe by considering their min Sentiment which are above

# 1- menCargo_df
balanced_menCargo_df = menCargo_df.groupby('Sentiment').apply(lambda x: x.sample(100)).reset_index(drop=True)

# 2- dinnerSet_df
balanced_dinnerSet_df = dinnerSet_df.groupby('Sentiment').apply(lambda x: x.sample(98)).reset_index(drop=True)

# 3- lakmeKajal_df
balanced_lakmeKajal_df = lakmeKajal_df.groupby('Sentiment').apply(lambda x: x.sample(100)).reset_index(drop=True)

# 4- elctricKettle_df
balanced_elctricKettle_df = elctricKettle_df.groupby('Sentiment').apply(lambda x: x.sample(97)).reset_index(drop=True)

# 5- windowCurtain_df
balanced_windowCurtain_df = windowCurtain_df.groupby('Sentiment').apply(lambda x: x.sample(75)).reset_index(drop=True)

# 6- memoryCard_df
balanced_dslrCamera_df = dslrCamera_df.groupby('Sentiment').apply(lambda x: x.sample(70)).reset_index(drop=True)

# 7- blackTshirt_df
balanced_blackTshirt_df = blackTshirt_df.groupby('Sentiment').apply(lambda x: x.sample(99)).reset_index(drop=True)

# 8- dryIron_df
balanced_dryIron_df = dryIron_df.groupby('Sentiment').apply(lambda x: x.sample(100)).reset_index(drop=True)

# 9- cusionPack_df
balanced_cusionPack_df = cusionPack_df.groupby('Sentiment').apply(lambda x: x.sample(96)).reset_index(drop=True)

# 10- googleAssistant_df
balanced_googleAssistant_df = googleAssistant_df.groupby('Sentiment').apply(lambda x: x.sample(77)).reset_index(drop=True)

# 11- airCooler_65_df
balanced_airCooler_65_df = airCooler_65_df.groupby('Sentiment').apply(lambda x: x.sample(34)).reset_index(drop=True)

# 12- airCooler_75_df
balanced_airCooler_75_df = airCooler_75_df.groupby('Sentiment').apply(lambda x: x.sample(40)).reset_index(drop=True)

C:\Users\pc\AppData\Local\Temp\ipykernel_28212\1740026374.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  balanced_menCargo_df = menCargo_df.groupby('Sentiment').apply(lambda x: x.sample(100)).reset_index(drop=True)
C:\Users\pc\AppData\Local\Temp\ipykernel_28212\1740026374.py:8: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  balanced_dinnerSet_df = dinnerSet_df.groupby('Sentiment').apply(lambda x: x.sample(98)).reset_index(drop=True)
C:\Users\pc\AppData\Local\Temp\ipykernel_28212\1740026374.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  balanced_lakmeKajal_df = lakmeKajal_df.groupby('Sentiment').apply(lambda x: x.sample(100)).reset_index(drop=True)
C:\Users\pc\AppData\Local\Temp\ipykernel_28212\1740026374.py:14: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  balanced_elctricKettle_df = elctricKettle_df.groupby('Sentiment').apply(lambda x: x.sample(97)).reset_index(drop=True)
C:\Users\pc\AppData\Local\Temp\ipykernel_28212\1740026374.py:17: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  balanced_windowCurtain_df = windowCurtain_df.groupby('Sentiment').apply(lambda x: x.sample(75)).reset_index(drop=True)
C:\Users\pc\AppData\Local\Temp\ipykernel_28212\1740026374.py:20: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  balanced_dslrCamera_df = dslrCamera_df.groupby('Sentiment').apply(lambda x: x.sample(70)).reset_index(drop=True)
C:\Users\pc\AppData\Local\Temp\ipykernel_28212\1740026374.py:23: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  balanced_blackTshirt_df = blackTshirt_df.groupby('Sentiment').apply(lambda x: x.sample(99)).reset_index(drop=True)
C:\Users\pc\AppData\Local\Temp\ipykernel_28212\1740026374.py:26: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  balanced_dryIron_df = dryIron_df.groupby('Sentiment').apply(lambda x: x.sample(100)).reset_index(drop=True)
C:\Users\pc\AppData\Local\Temp\ipykernel_28212\1740026374.py:29: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  balanced_cusionPack_df = cusionPack_df.groupby('Sentiment').apply(lambda x: x.sample(96)).reset_index(drop=True)
C:\Users\pc\AppData\Local\Temp\ipykernel_28212\1740026374.py:32: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  balanced_googleAssistant_df = googleAssistant_df.groupby('Sentiment').apply(lambda x: x.sample(77)).reset_index(drop=True)
C:\Users\pc\AppData\Local\Temp\ipykernel_28212\1740026374.py:35: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  balanced_airCooler_65_df = airCooler_65_df.groupby('Sentiment').apply(lambda x: x.sample(34)).reset_index(drop=True)
C:\Users\pc\AppData\Local\Temp\ipykernel_28212\1740026374.py:38: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  balanced_airCooler_75_df = airCooler_75_df.groupby('Sentiment').apply(lambda x: x.sample(40)).reset_index(drop=True)

The reason for taking not more than 100 samples for each class is to balance the dataset in such a way that it not affect the model's accuracy, because we also have those products which has min 70 reviews per class. 
So each product has max of 100 reviews per class.

concatinating our product datasets to make new balanced dataframe

In [71]:
balanced_df = pd.concat([balanced_airCooler_65_df, balanced_airCooler_75_df, balanced_blackTshirt_df, 
                         balanced_cusionPack_df, balanced_dinnerSet_df, balanced_dryIron_df, balanced_dslrCamera_df, 
                        balanced_elctricKettle_df, balanced_googleAssistant_df, balanced_lakmeKajal_df, balanced_menCargo_df, 
                        balanced_windowCurtain_df], axis=0)

balanced_df

,product_name,product_price,Rate,Review,Summary,Sentiment
0,MAHARAJA WHITELINE 65 L Desert Air Cooler?????...,7999,1,hated it!,not that good that mentioned,negative
1,MAHARAJA WHITELINE 65 L Desert Air Cooler?????...,7999,3,just okay,good bt without wheel or stand very difficult ...,negative
2,MAHARAJA WHITELINE 65 L Desert Air Cooler?????...,7999,1,worst experience ever!,worst,negative
3,MAHARAJA WHITELINE 65 L Desert Air Cooler?????...,7999,1,not recommended at all,send damage product dont buy,negative
4,MAHARAJA WHITELINE 65 L Desert Air Cooler?????...,7999,2,not good,worst,negative
...,...,...,...,...,...,...
220,Home Sizzler 153 cm 502 ft Polyester Room Dark...,299,5,terrific purchase,orginal colour value for money,positive
221,Home Sizzler 153 cm 502 ft Polyester Room Dark...,299,5,great product,i was totally loved it same as shown in the pi...,positive
222,Home Sizzler 153 cm 502 ft Polyester Room Dark...,299,5,simply awesome,great and useful product,positive
223,Home Sizzler 153 cm 502 ft Polyester Room Dark...,299,5,perfect product!,good products,positive
224,Home Sizzler 153 cm 502 ft Polyester Room Dark...,299,5,highly recommended,very nice,positive

In [73]:
balanced_df['Sentiment'].value_counts()

Sentiment
negative    986
neutral     986
positive    986
Name: count, dtype: int64

In [75]:
balanced_df['product_name'].value_counts()

product_name
Bajaj DX 2 LW Dry Iron                                                                                             300
Lakm?? Eyeconic Kajal Twin Pack??????????(Deep Black, 0.7 g)                                                       300
Men Cargos                                                                                                         300
Men Graphic Print Round Neck Black T-Shirt                                                                         297
cello Pack of 18 Opalware Cello Dazzle Lush Fiesta Opalware Dinner Set 18 Pieces Dinner SetWhite Microwave Safe    294
Pigeon Favourite Electric Kettle??????(1.5 L, Silver, Black)                                                       291
LA VERNE Microfibre Stripes Cushion Pack of 3White                                                                 288
Google Nest Mini (2nd Gen) with Google Assistant Smart Speaker??????(Chalk)                                        231
Home Sizzler 153 cm 502 ft Polyester Room Darkening Window Curtain Pack Of 2Floral Brown                           225
Canon EOS 3000D DSLR Camera 1 Camera Body, 18 - 55 mm Lens????????(Black)                                          210
Crompton 75 L Desert Air Cooler??????(White, Teal, ACGC-DAC751)                                                    120
MAHARAJA WHITELINE 65 L Desert Air Cooler??????(White, Grey, Rambo Grey / AC-303)                                  102
Name: count, dtype: int64

In [79]:
prod = balanced_df['product_name'].value_counts()

prod.index

Index(['Bajaj DX 2 LW Dry Iron',
       'Lakm?? Eyeconic Kajal Twin Pack??????????(Deep Black, 0.7 g)',
       'Men Cargos', 'Men Graphic Print Round Neck Black T-Shirt',
       'cello Pack of 18 Opalware Cello Dazzle Lush Fiesta Opalware Dinner Set 18 Pieces Dinner SetWhite Microwave Safe',
       'Pigeon Favourite Electric Kettle??????(1.5 L, Silver, Black)',
       'LA VERNE Microfibre Stripes Cushion Pack of 3White',
       'Google Nest Mini (2nd Gen) with Google Assistant Smart Speaker??????(Chalk)',
       'Home Sizzler 153 cm 502 ft Polyester Room Darkening Window Curtain Pack Of 2Floral Brown',
       'Canon EOS 3000D DSLR Camera 1 Camera Body, 18 - 55 mm Lens????????(Black)',
       'Crompton 75 L Desert Air Cooler??????(White, Teal, ACGC-DAC751)',
       'MAHARAJA WHITELINE 65 L Desert Air Cooler??????(White, Grey, Rambo Grey / AC-303)'],
      dtype='object', name='product_name')

In [233]:
balanced_df_new = pd.DataFrame()

balanced_df_new['review'] = balanced_df['Summary']
balanced_df_new['sentiment'] = balanced_df['Sentiment']

In [93]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(balanced_df['product_name'], balanced_df.Sentiment, test_size=0.2)

In [95]:
X_train

203    LA VERNE Microfibre Stripes Cushion Pack of 3W...
63     Lakm?? Eyeconic Kajal Twin Pack??????????(Deep...
103           Men Graphic Print Round Neck Black T-Shirt
217    Google Nest Mini (2nd Gen) with Google Assista...
179    Lakm?? Eyeconic Kajal Twin Pack??????????(Deep...
                             ...
182    Canon EOS 3000D DSLR Camera 1 Camera Body, 18 ...
172           Men Graphic Print Round Neck Black T-Shirt
24     Crompton 75 L Desert Air Cooler??????(White, T...
8      LA VERNE Microfibre Stripes Cushion Pack of 3W...
67     MAHARAJA WHITELINE 65 L Desert Air Cooler?????...
Name: product_name, Length: 2366, dtype: object

In [97]:
y_train

203    positive
63     negative
103     neutral
217    positive
179     neutral
         ...
182    positive
172     neutral
24     negative
8      negative
67      neutral
Name: Sentiment, Length: 2366, dtype: object

In [ ]:
X_train.

In [235]:
# Now saving our balanced dataframe

balanced_df_new.to_csv('balanced_dataset.csv')